// Autogenerated by Thrift Compiler (0.14.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

#![allow(unused_imports)]
#![allow(unused_extern_crates)]
#![allow(clippy::too_many_arguments, clippy::type_complexity)]
#![cfg_attr(rustfmt, rustfmt_skip)]


use thrift::OrderedFloat;
use std::cell::RefCell;
use std::collections::{BTreeMap, BTreeSet};
use std::convert::{From, TryFrom};
use std::default::Default;
use std::error::Error;
use std::fmt;
use std::fmt::{Display, Formatter};
use std::rc::Rc;

use thrift::{ApplicationError, ApplicationErrorKind, ProtocolError, ProtocolErrorKind, TThriftClient};
use thrift::protocol::{TFieldIdentifier, TListIdentifier, TMapIdentifier, TMessageIdentifier, TMessageType, TAsyncInputProtocol, TAsyncOutputProtocol, TSetIdentifier, TStructIdentifier, TType};
use thrift::protocol::field_id;
use thrift::protocol::verify_expected_message_type;
use thrift::protocol::verify_expected_sequence_number;
use thrift::protocol::verify_expected_service_call;
use thrift::protocol::verify_required_field_exists;
use thrift::server::TAsyncProcessor;

// For Rust Thrift Async

use async_trait::async_trait;


// Definition for async trait

#[async_trait]
pub trait TRWProtocol<T> {
  async fn read_from_in_protocol(i_prot: &mut (dyn TAsyncInputProtocol + Send)) -> thrift::Result<T>;
  async fn write_to_out_protocol(&self, o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()>;
}

//
// SharedService service client
//

/// This Thrift file can be included by other Thrift files that want to share
/// these definitions.
// Magic number: 09011020 generate for client async trait
#[async_trait]
pub trait TSharedServiceSyncClient {
  async fn add(&mut self, arg1: i32, arg2: i32) -> thrift::Result<i32>;
  async fn send_packet(&mut self, str: String) -> thrift::Result<String>;
  async fn send_empty(&mut self) -> thrift::Result<()>;
}

pub trait TSharedServiceSyncClientMarker {}

pub struct SharedServiceSyncClient<IP, OP> where IP: TAsyncInputProtocol, OP: TAsyncOutputProtocol {
  _i_prot: IP,
  _o_prot: OP,
  _sequence_number: i32,
}

impl <IP, OP> SharedServiceSyncClient<IP, OP> where IP: TAsyncInputProtocol, OP: TAsyncOutputProtocol {
  pub fn new(input_protocol: IP, output_protocol: OP) -> SharedServiceSyncClient<IP, OP> {
    SharedServiceSyncClient { _i_prot: input_protocol, _o_prot: output_protocol, _sequence_number: 0 }
  }
}

impl <IP, OP> TThriftClient for SharedServiceSyncClient<IP, OP> where IP: TAsyncInputProtocol + Send, OP: TAsyncOutputProtocol + Send {
  fn i_prot_mut(&mut self) -> &mut (dyn TAsyncInputProtocol + Send) { &mut self._i_prot }
  fn o_prot_mut(&mut self) -> &mut (dyn TAsyncOutputProtocol + Send) { &mut self._o_prot }
  fn sequence_number(&self) -> i32 { self._sequence_number }
  fn increment_sequence_number(&mut self) -> i32 { self._sequence_number += 1; self._sequence_number }
}

impl <IP, OP> TSharedServiceSyncClientMarker for SharedServiceSyncClient<IP, OP> where IP: TAsyncInputProtocol, OP: TAsyncOutputProtocol {}

// Magic number:09011023 generate for client_process impl
#[async_trait]
impl <C: TThriftClient + TSharedServiceSyncClientMarker + Send> TSharedServiceSyncClient for C {
  async fn add(&mut self, arg1: i32, arg2: i32) -> thrift::Result<i32> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("add", TMessageType::Call, self.sequence_number());
        let call_args = SharedServiceAddArgs { arg1: arg1, arg2: arg2 };
        self.o_prot_mut().write_message_begin(&message_ident).await?;
        call_args.write_to_out_protocol(self.o_prot_mut()).await?;
        self.o_prot_mut().write_message_end().await?;
        self.o_prot_mut().flush().await
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin().await?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("add", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut()).await?;
        self.i_prot_mut().read_message_end().await?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = SharedServiceAddResult::read_from_in_protocol(self.i_prot_mut()).await?;
      self.i_prot_mut().read_message_end().await?;
      result.ok_or()
    }
  }
  async fn send_packet(&mut self, str: String) -> thrift::Result<String> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("send_packet", TMessageType::Call, self.sequence_number());
        let call_args = SharedServiceSendPacketArgs { str: str };
        self.o_prot_mut().write_message_begin(&message_ident).await?;
        call_args.write_to_out_protocol(self.o_prot_mut()).await?;
        self.o_prot_mut().write_message_end().await?;
        self.o_prot_mut().flush().await
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin().await?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("send_packet", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut()).await?;
        self.i_prot_mut().read_message_end().await?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = SharedServiceSendPacketResult::read_from_in_protocol(self.i_prot_mut()).await?;
      self.i_prot_mut().read_message_end().await?;
      result.ok_or()
    }
  }
  async fn send_empty(&mut self) -> thrift::Result<()> {
    (
      {
        self.increment_sequence_number();
        let message_ident = TMessageIdentifier::new("send_empty", TMessageType::Call, self.sequence_number());
        let call_args = SharedServiceSendEmptyArgs {  };
        self.o_prot_mut().write_message_begin(&message_ident).await?;
        call_args.write_to_out_protocol(self.o_prot_mut()).await?;
        self.o_prot_mut().write_message_end().await?;
        self.o_prot_mut().flush().await
      }
    )?;
    {
      let message_ident = self.i_prot_mut().read_message_begin().await?;
      verify_expected_sequence_number(self.sequence_number(), message_ident.sequence_number)?;
      verify_expected_service_call("send_empty", &message_ident.name)?;
      if message_ident.message_type == TMessageType::Exception {
        let remote_error = thrift::Error::read_application_error_from_in_protocol(self.i_prot_mut()).await?;
        self.i_prot_mut().read_message_end().await?;
        return Err(thrift::Error::Application(remote_error))
      }
      verify_expected_message_type(TMessageType::Reply, message_ident.message_type)?;
      let result = SharedServiceSendEmptyResult::read_from_in_protocol(self.i_prot_mut()).await?;
      self.i_prot_mut().read_message_end().await?;
      result.ok_or()
    }
  }
}

//
// SharedService service processor
//

/// This Thrift file can be included by other Thrift files that want to share
/// these definitions.

// Magic number:091037 generate handler async trait
#[async_trait]
pub trait SharedServiceSyncHandler {
  async fn handle_add(&self, arg1: i32, arg2: i32) -> thrift::Result<i32>;
  async fn handle_send_packet(&self, str: String) -> thrift::Result<String>;
  async fn handle_send_empty(&self) -> thrift::Result<()>;
}
// Magic number:09011500 at the end

pub struct SharedServiceSyncProcessor<H: SharedServiceSyncHandler + Send + std::marker::Sync> {
  handler: H,
}

impl <H: SharedServiceSyncHandler + Send + std::marker::Sync> SharedServiceSyncProcessor<H> {
  pub fn new(handler: H) -> SharedServiceSyncProcessor<H> {
    SharedServiceSyncProcessor {
      handler,
    }
  }
 // Magic Number: 09011505 before render sync process delegation
  async fn process_add(&self, incoming_sequence_number: i32, i_prot: &mut (dyn TAsyncInputProtocol + Send), o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    TSharedServiceProcessFunctions::process_add(&self.handler, incoming_sequence_number, i_prot, o_prot).await
  }
  async fn process_send_packet(&self, incoming_sequence_number: i32, i_prot: &mut (dyn TAsyncInputProtocol + Send), o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    TSharedServiceProcessFunctions::process_send_packet(&self.handler, incoming_sequence_number, i_prot, o_prot).await
  }
  async fn process_send_empty(&self, incoming_sequence_number: i32, i_prot: &mut (dyn TAsyncInputProtocol + Send), o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    TSharedServiceProcessFunctions::process_send_empty(&self.handler, incoming_sequence_number, i_prot, o_prot).await
  }
 // Magic Number: 09011506 after render sync process delegation
}

pub struct TSharedServiceProcessFunctions;

impl TSharedServiceProcessFunctions {
  pub async fn process_add<H: SharedServiceSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut (dyn TAsyncInputProtocol + Send), o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    let args = SharedServiceAddArgs::read_from_in_protocol(i_prot).await?;
    match handler.handle_add(args.arg1, args.arg2).await {
      Ok(handler_return) => {
        let message_ident = TMessageIdentifier::new("add", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident).await?;
        let ret = SharedServiceAddResult { result_value: Some(handler_return) };
        ret.write_to_out_protocol(o_prot).await?;
        o_prot.write_message_end().await?;
        o_prot.flush().await
      },
      Err(e) => {
        // Magic num: 09011535 before handler failed
        match e {
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("add", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident).await?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot).await?;
            o_prot.write_message_end().await?;
            o_prot.flush().await
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.description()
              )
            };
            let message_ident = TMessageIdentifier::new("add", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident).await?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot).await?;
            o_prot.write_message_end().await?;
            o_prot.flush().await
          },
        }
        // Magic num: 09011535 after handler failed
      },
    }
  }
  pub async fn process_send_packet<H: SharedServiceSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut (dyn TAsyncInputProtocol + Send), o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    let args = SharedServiceSendPacketArgs::read_from_in_protocol(i_prot).await?;
    match handler.handle_send_packet(args.str).await {
      Ok(handler_return) => {
        let message_ident = TMessageIdentifier::new("send_packet", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident).await?;
        let ret = SharedServiceSendPacketResult { result_value: Some(handler_return) };
        ret.write_to_out_protocol(o_prot).await?;
        o_prot.write_message_end().await?;
        o_prot.flush().await
      },
      Err(e) => {
        // Magic num: 09011535 before handler failed
        match e {
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("send_packet", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident).await?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot).await?;
            o_prot.write_message_end().await?;
            o_prot.flush().await
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.description()
              )
            };
            let message_ident = TMessageIdentifier::new("send_packet", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident).await?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot).await?;
            o_prot.write_message_end().await?;
            o_prot.flush().await
          },
        }
        // Magic num: 09011535 after handler failed
      },
    }
  }
  pub async fn process_send_empty<H: SharedServiceSyncHandler>(handler: &H, incoming_sequence_number: i32, i_prot: &mut (dyn TAsyncInputProtocol + Send), o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    let _ = SharedServiceSendEmptyArgs::read_from_in_protocol(i_prot).await?;
    match handler.handle_send_empty().await {
      Ok(_) => {
        let message_ident = TMessageIdentifier::new("send_empty", TMessageType::Reply, incoming_sequence_number);
        o_prot.write_message_begin(&message_ident).await?;
        let ret = SharedServiceSendEmptyResult {  };
        ret.write_to_out_protocol(o_prot).await?;
        o_prot.write_message_end().await?;
        o_prot.flush().await
      },
      Err(e) => {
        // Magic num: 09011535 before handler failed
        match e {
          thrift::Error::Application(app_err) => {
            let message_ident = TMessageIdentifier::new("send_empty", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident).await?;
            thrift::Error::write_application_error_to_out_protocol(&app_err, o_prot).await?;
            o_prot.write_message_end().await?;
            o_prot.flush().await
          },
          _ => {
            let ret_err = {
              ApplicationError::new(
                ApplicationErrorKind::Unknown,
                e.description()
              )
            };
            let message_ident = TMessageIdentifier::new("send_empty", TMessageType::Exception, incoming_sequence_number);
            o_prot.write_message_begin(&message_ident).await?;
            thrift::Error::write_application_error_to_out_protocol(&ret_err, o_prot).await?;
            o_prot.write_message_end().await?;
            o_prot.flush().await
          },
        }
        // Magic num: 09011535 after handler failed
      },
    }
  }
}

#[async_trait]
impl <H: SharedServiceSyncHandler + Send + Sync> TAsyncProcessor for SharedServiceSyncProcessor<H> {
  async fn process(&self, i_prot: &mut (dyn TAsyncInputProtocol + Send), o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    let message_ident = i_prot.read_message_begin().await?;
    let res = match &*message_ident.name {
// Magic number: 09010345 before render process match statesment
      "add" => {
        self.process_add(message_ident.sequence_number, i_prot, o_prot).await
      },
      "send_packet" => {
        self.process_send_packet(message_ident.sequence_number, i_prot, o_prot).await
      },
      "send_empty" => {
        self.process_send_empty(message_ident.sequence_number, i_prot, o_prot).await
      },
// Magic number: 09010345 after render process match statesment
      method => {
        println!("[gbd] process error here");
        Err(
          thrift::Error::Application(
            ApplicationError::new(
              ApplicationErrorKind::UnknownMethod,
              format!("unknown method {}", method)
            )
          )
        )
      },
    };
    thrift::server::handle_process_result(&message_ident, res, o_prot).await
  }
}

//
// SharedServiceAddArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct SharedServiceAddArgs {
  arg1: i32,
  arg2: i32,
}

impl SharedServiceAddArgs {
}

// Magic number:911001 generate async trait imple for SharedServiceAddArgs
#[async_trait]
impl TRWProtocol<SharedServiceAddArgs> for SharedServiceAddArgs {
  async fn read_from_in_protocol(i_prot: &mut (dyn TAsyncInputProtocol + Send)) -> thrift::Result<SharedServiceAddArgs> {
    i_prot.read_struct_begin().await?;
    let mut f_1: Option<i32> = None;
    let mut f_2: Option<i32> = None;
    loop {
      let field_ident = i_prot.read_field_begin().await?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_i32().await?;
          f_1 = Some(val);
        },
        2 => {
          let val = i_prot.read_i32().await?;
          f_2 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type).await?;
        },
      };
      i_prot.read_field_end().await?;
    }
    i_prot.read_struct_end().await?;
    verify_required_field_exists("SharedServiceAddArgs.arg1", &f_1)?;
    verify_required_field_exists("SharedServiceAddArgs.arg2", &f_2)?;
    let ret = SharedServiceAddArgs {
      arg1: f_1.expect("auto-generated code should have checked for presence of required fields"),
      arg2: f_2.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  async fn write_to_out_protocol(&self, o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("add_args");
    o_prot.write_struct_begin(&struct_ident).await?;
    o_prot.write_field_begin(&TFieldIdentifier::new("arg1", TType::I32, 1)).await?;
    o_prot.write_i32(self.arg1).await?;
    o_prot.write_field_end().await?;
    o_prot.write_field_begin(&TFieldIdentifier::new("arg2", TType::I32, 2)).await?;
    o_prot.write_i32(self.arg2).await?;
    o_prot.write_field_end().await?;
    o_prot.write_field_stop().await?;
    o_prot.write_struct_end().await
  }
}

//
// SharedServiceAddResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct SharedServiceAddResult {
  result_value: Option<i32>,
}

impl SharedServiceAddResult {
  fn ok_or(self) -> thrift::Result<i32> {
    if self.result_value.is_some() {
      Ok(self.result_value.unwrap())
    } else {
      Err(
        thrift::Error::Application(
          ApplicationError::new(
            ApplicationErrorKind::MissingResult,
            "no result received for SharedServiceAdd"
          )
        )
      )
    }
  }
}

// Magic number:911001 generate async trait imple for SharedServiceAddResult
#[async_trait]
impl TRWProtocol<SharedServiceAddResult> for SharedServiceAddResult {
  async fn read_from_in_protocol(i_prot: &mut (dyn TAsyncInputProtocol + Send)) -> thrift::Result<SharedServiceAddResult> {
    i_prot.read_struct_begin().await?;
    let mut f_0: Option<i32> = None;
    loop {
      let field_ident = i_prot.read_field_begin().await?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        0 => {
          let val = i_prot.read_i32().await?;
          f_0 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type).await?;
        },
      };
      i_prot.read_field_end().await?;
    }
    i_prot.read_struct_end().await?;
    let ret = SharedServiceAddResult {
      result_value: f_0,
    };
    Ok(ret)
  }
  async fn write_to_out_protocol(&self, o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("SharedServiceAddResult");
    o_prot.write_struct_begin(&struct_ident).await?;
    if let Some(fld_var) = self.result_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("result_value", TType::I32, 0)).await?;
      o_prot.write_i32(fld_var).await?;
      o_prot.write_field_end().await?;
      ()
    } else {
      ()
    }
    o_prot.write_field_stop().await?;
    o_prot.write_struct_end().await
  }
}

//
// SharedServiceSendPacketArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct SharedServiceSendPacketArgs {
  str: String,
}

impl SharedServiceSendPacketArgs {
}

// Magic number:911001 generate async trait imple for SharedServiceSendPacketArgs
#[async_trait]
impl TRWProtocol<SharedServiceSendPacketArgs> for SharedServiceSendPacketArgs {
  async fn read_from_in_protocol(i_prot: &mut (dyn TAsyncInputProtocol + Send)) -> thrift::Result<SharedServiceSendPacketArgs> {
    i_prot.read_struct_begin().await?;
    let mut f_1: Option<String> = None;
    loop {
      let field_ident = i_prot.read_field_begin().await?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        1 => {
          let val = i_prot.read_string().await?;
          f_1 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type).await?;
        },
      };
      i_prot.read_field_end().await?;
    }
    i_prot.read_struct_end().await?;
    verify_required_field_exists("SharedServiceSendPacketArgs.str", &f_1)?;
    let ret = SharedServiceSendPacketArgs {
      str: f_1.expect("auto-generated code should have checked for presence of required fields"),
    };
    Ok(ret)
  }
  async fn write_to_out_protocol(&self, o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("send_packet_args");
    o_prot.write_struct_begin(&struct_ident).await?;
    o_prot.write_field_begin(&TFieldIdentifier::new("str", TType::String, 1)).await?;
    o_prot.write_string(&self.str).await?;
    o_prot.write_field_end().await?;
    o_prot.write_field_stop().await?;
    o_prot.write_struct_end().await
  }
}

//
// SharedServiceSendPacketResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct SharedServiceSendPacketResult {
  result_value: Option<String>,
}

impl SharedServiceSendPacketResult {
  fn ok_or(self) -> thrift::Result<String> {
    if self.result_value.is_some() {
      Ok(self.result_value.unwrap())
    } else {
      Err(
        thrift::Error::Application(
          ApplicationError::new(
            ApplicationErrorKind::MissingResult,
            "no result received for SharedServiceSendPacket"
          )
        )
      )
    }
  }
}

// Magic number:911001 generate async trait imple for SharedServiceSendPacketResult
#[async_trait]
impl TRWProtocol<SharedServiceSendPacketResult> for SharedServiceSendPacketResult {
  async fn read_from_in_protocol(i_prot: &mut (dyn TAsyncInputProtocol + Send)) -> thrift::Result<SharedServiceSendPacketResult> {
    i_prot.read_struct_begin().await?;
    let mut f_0: Option<String> = None;
    loop {
      let field_ident = i_prot.read_field_begin().await?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        0 => {
          let val = i_prot.read_string().await?;
          f_0 = Some(val);
        },
        _ => {
          i_prot.skip(field_ident.field_type).await?;
        },
      };
      i_prot.read_field_end().await?;
    }
    i_prot.read_struct_end().await?;
    let ret = SharedServiceSendPacketResult {
      result_value: f_0,
    };
    Ok(ret)
  }
  async fn write_to_out_protocol(&self, o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("SharedServiceSendPacketResult");
    o_prot.write_struct_begin(&struct_ident).await?;
    if let Some(ref fld_var) = self.result_value {
      o_prot.write_field_begin(&TFieldIdentifier::new("result_value", TType::String, 0)).await?;
      o_prot.write_string(fld_var).await?;
      o_prot.write_field_end().await?;
      ()
    } else {
      ()
    }
    o_prot.write_field_stop().await?;
    o_prot.write_struct_end().await
  }
}

//
// SharedServiceSendEmptyArgs
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct SharedServiceSendEmptyArgs {
}

impl SharedServiceSendEmptyArgs {
}

// Magic number:911001 generate async trait imple for SharedServiceSendEmptyArgs
#[async_trait]
impl TRWProtocol<SharedServiceSendEmptyArgs> for SharedServiceSendEmptyArgs {
  async fn read_from_in_protocol(i_prot: &mut (dyn TAsyncInputProtocol + Send)) -> thrift::Result<SharedServiceSendEmptyArgs> {
    i_prot.read_struct_begin().await?;
    loop {
      let field_ident = i_prot.read_field_begin().await?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        _ => {
          i_prot.skip(field_ident.field_type).await?;
        },
      };
      i_prot.read_field_end().await?;
    }
    i_prot.read_struct_end().await?;
    let ret = SharedServiceSendEmptyArgs {};
    Ok(ret)
  }
  async fn write_to_out_protocol(&self, o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("send_empty_args");
    o_prot.write_struct_begin(&struct_ident).await?;
    o_prot.write_field_stop().await?;
    o_prot.write_struct_end().await
  }
}

//
// SharedServiceSendEmptyResult
//

#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct SharedServiceSendEmptyResult {
}

impl SharedServiceSendEmptyResult {
  fn ok_or(self) -> thrift::Result<()> {
    Ok(())
  }
}

// Magic number:911001 generate async trait imple for SharedServiceSendEmptyResult
#[async_trait]
impl TRWProtocol<SharedServiceSendEmptyResult> for SharedServiceSendEmptyResult {
  async fn read_from_in_protocol(i_prot: &mut (dyn TAsyncInputProtocol + Send)) -> thrift::Result<SharedServiceSendEmptyResult> {
    i_prot.read_struct_begin().await?;
    loop {
      let field_ident = i_prot.read_field_begin().await?;
      if field_ident.field_type == TType::Stop {
        break;
      }
      let field_id = field_id(&field_ident)?;
      match field_id {
        _ => {
          i_prot.skip(field_ident.field_type).await?;
        },
      };
      i_prot.read_field_end().await?;
    }
    i_prot.read_struct_end().await?;
    let ret = SharedServiceSendEmptyResult {};
    Ok(ret)
  }
  async fn write_to_out_protocol(&self, o_prot: &mut (dyn TAsyncOutputProtocol + Send)) -> thrift::Result<()> {
    let struct_ident = TStructIdentifier::new("SharedServiceSendEmptyResult");
    o_prot.write_struct_begin(&struct_ident).await?;
    o_prot.write_field_stop().await?;
    o_prot.write_struct_end().await
  }
}

